Lesson6 bdd
HelenRaven/QnA pull request #3
Opened 2021-02-17 10:48 UTC by HelenRaven

2021-02-17 20:18 UTC, IvanShamatov requested changes

2021-02-17 20:18 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  def author?
лучше этот метод реализовать в модели user'a, и спрашивтаь if current_user.author?(object)...

2021-02-17 20:18 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  helper_method :answer, :question, :author?
хелпер методы доступны из вьюше. Вопрос на засыпку: какой из этиих двух хелперов (из разных контроллеров) сработает, если мы откроем вьюшку

2021-02-17 20:18 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +    before { login(answer.user) }
не хватает спек на все экшены, когда приходит не автор и пытается что-то сделать с ответом и вопросом. Эти сценарии не описаны

2021-02-17 20:18 UTC, IvanShamatov commented on spec/features/answer/delete_spec.rb
> +  scenario 'Authenticated author try to delete his answer' do
не хватает спеки для неавторизованного пользователя

2021-02-18 09:06 UTC, vkurennov requested changes

2021-02-18 09:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    flash[:notice] = if @answer.save
вот это не очень удачное решение, валидаций может быть больше, чем одна и они должны из модели быть получены. чтобы ошибки не пропадали, в случае, если ответ невалидный, надо делать рендер страницы 'questions/show'

2021-02-18 09:06 UTC, vkurennov commented on app/models/user.rb
> +    self == object.user
в целом, верно, но здесь из базы грузится в память целый объект (ассоциация user), но по факту он не использщуется. Лучше сравнивать по user_id, т.к. это поле уже загружено в память.

2021-02-18 09:06 UTC, vkurennov commented on spec/features/question/view_with_answers_spec.rb
> +  given(:answer) { create(:answer) }
тут должен быть список, а не один ответ. и проверять надо в цикле, поэтому ответы должны быть разными (можно использовать sequence в фабриках)

2021-02-18 09:06 UTC, vkurennov commented on spec/features/question/view_all_spec.rb
> +    expect(page).to have_content 'MyString'
проверять надо весь список вопросов, причем, они должны быть разными

2021-02-18 09:06 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где же тесты метода `author?`, любой код, который ты пишешь, должен покрываться тестами

2021-02-19 08:49 UTC, vkurennov requested changes

2021-02-19 08:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @answer.errors.full_messages.each do |message|
и вновь не лучшее решение, лучше сделать render 'questions/show' в случае ошибок валидации

2021-02-19 08:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).to have_content 'Your answer was successfully deleted.'
тут надо бы проверить, что ответа больше нет на странице

2021-02-19 08:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    visit answer_path(answer)
а зачем ответу отдельная страница? все ответы должны быть на странице вопроса

2021-02-19 08:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_content 'Your question was successfully deleted.'
тут тоже стоит проверить, что после удаления, вопроса нет на странице

2021-02-19 08:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to_not have_content 'Delete question'
для проверки ссылок лучше have_link использовать

2021-02-19 08:49 UTC, vkurennov commented on spec/features/question/view_with_answers_spec.rb
> +    questions.each do |question|
это стоило сделать через фабрики. и потом в тесте через create_list создать не вопросы, а ответы

2021-02-19 08:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +  describe '.author?' do
только название инстанс-метода принято с решетки начинать, с точки - это методы класса

2021-02-19 08:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it { expect(question.user.author?(question)).to be true }
1. длинная конструкция. ты свяжи сразу юзера и вопрос, еще на уровне let, тогда не надо будет обращаться к question.user
2. для методов-предикатов в rspec есть особый синтаксис, можно писать так: 
`expect(user).to be_author(question)`

т.е. переносим вызов метода вправо, добавляем be_, убираем знак вопроса.

2021-02-19 08:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +      it { expect(answer.user.author?(answer)).to be true }
метод универсальный, поэтому достаточно на одном (любом) объекте проверить

2021-02-19 08:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    # не могу придумать, каким способом передать ошибку несохраненного ответа в show вопроса
я ниже написал, делаешь `render 'question/show'` и все

2021-02-19 15:16 UTC, vkurennov approved these changes

2021-02-22 10:24 UTC, merged